#!/usr/bin/env python3
"""
gen_dense_control.py -- generates control_unit.v, alu_control.v, and
alu.v using DENSE (minimal-width) alu_op / alu_control / mem_to_reg
encodings from encoding_plan.py, instead of the original fixed-width
encodings.

Every one of the three generated modules is derived from the SAME
encoding_plan.compute_plan() call in main() below, so alu_op/alu_control
codes are guaranteed consistent between the module that assigns them
(control_unit.v, alu_control.v) and the module that consumes them
(alu_control.v, alu.v) -- see encoding_plan.py's module docstring for why
that matters.

REPLACES gen_control_from_insts.py's rendering of JUST these three files
(control_unit.v.j2 / alu_control.v.j2 / alu.v.j2). branch_unit.v and
register_file.v are unaffected by this and should still be generated by
gen_control_from_insts.py as before.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import encoding_plan as ep


# ---------------------------------------------------------------------------
# control_unit.v
# ---------------------------------------------------------------------------

def gen_control_unit(plan: dict, instructions_used: set) -> str:
    aow = plan["alu_op_width"]
    mtw = plan["mem_to_reg_width"]
    aoc = plan["alu_op_codes"]
    mtc = plan["mem_to_reg_codes"]

    def aop(name: str) -> str:
        return f"{aow}'d{aoc[name]}"

    def mtr(name: str) -> str:
        return f"{mtw}'d{mtc[name]}"

    has_r_type = bool(instructions_used & ep.R_TYPE_SET)
    has_i_alu = bool(instructions_used & ep.I_ALU_SET)
    has_load = bool(instructions_used & ep.LOAD_SET)
    has_store = bool(instructions_used & ep.STORE_SET)
    has_branch = bool(instructions_used & ep.BRANCH_SET)
    has_jal = "jal" in instructions_used
    has_jalr = "jalr" in instructions_used
    has_lui = "lui" in instructions_used
    has_auipc = "auipc" in instructions_used
    has_custom = any(str(i).startswith("custom_") for i in instructions_used)

    cases = []
    if has_r_type:
        cases.append(f"""            // R-type ALU ops: add, sub, and, or, xor, sll, srl, sra, slt, sltu
            7'b0110011: begin
                reg_write_internal = 1'b1;
                alu_op             = {aop('ialu')};
                alu_src            = 1'b0;
            end""")
    if has_i_alu:
        cases.append(f"""            // I-type ALU/immediate ops: addi, andi, ori, xori, slti, ...
            7'b0010011: begin
                reg_write_internal = 1'b1;
                alu_op             = {aop('ialu')};
                alu_src            = 1'b1;
            end""")
    if has_load:
        cases.append(f"""            // Loads: lw, lh, lb, lhu, lbu
            7'b0000011: begin
                reg_write_internal = 1'b1;
                mem_read           = 1'b1;
                alu_op             = {aop('addfam')};
                alu_src            = 1'b1;
                mem_to_reg         = {mtr('mem')};
            end""")
    if has_store:
        cases.append(f"""            // Stores: sw, sh, sb
            7'b0100011: begin
                mem_write          = 1'b1;
                alu_op             = {aop('addfam')};
                alu_src            = 1'b1;
            end""")
    if has_branch:
        cases.append(f"""            // Branches: beq, bne, blt, bge, bltu, bgeu
            7'b1100011: begin
                branch             = 1'b1;
                alu_op             = {aop('branch')};
                alu_src            = 1'b0;
            end""")
    if has_jal:
        cases.append(f"""            // JAL
            7'b1101111: begin
                reg_write_internal = 1'b1;
                jump               = 1'b1;
                mem_to_reg         = {mtr('pcplus4')};
                alu_src            = 1'b1;
            end""")
    if has_jalr:
        cases.append(f"""            // JALR
            7'b1100111: begin
                reg_write_internal = 1'b1;
                jump               = 1'b1;
                jalr               = 1'b1;
                mem_to_reg         = {mtr('pcplus4')};
                alu_src            = 1'b1;
                alu_op             = {aop('addfam')};
            end""")
    if has_lui:
        cases.append(f"""            // LUI
            7'b0110111: begin
                reg_write_internal = 1'b1;
                alu_src            = 1'b1;
                alu_op             = {aop('lui')};
            end""")
    if has_auipc:
        cases.append(f"""            // AUIPC
            7'b0010111: begin
                reg_write_internal = 1'b1;
                alu_src            = 1'b1;
                alu_op             = {aop('addfam')};
            end""")

    if has_custom:
        cases.append("""            // Custom instructions (custom_mul/mulh/mulhu/mac/reserved,
            // disambiguated by funct3 inside custom_unit.v, not here).
            // Register operands (rs1, rs2) -- alu_src stays at its
            // default 0. Result flows through ex_result -> alu_result_wb
            // regardless of alu_op (custom_en_ex selects custom_result_ex
            // directly, bypassing the ALU entirely), and write_back_data's
            // default "alu" source (mem_to_reg=0) already picks that up
            // correctly -- reg_write is the only signal this actually
            // needs. Missing this case entirely (falling through to
            // default, which never asserts reg_write) was a real,
            // previously-unresolved bug: the custom instruction's result
            // computed correctly through the datapath, but never
            // committed to the register file. Confirmed via simulation:
            // a custom_mul(6,7) computed 42 on the write-back bus every
            // time, but the destination register stayed at whatever
            // value it held before the instruction ever ran.
            7'b0001011: begin
                reg_write_internal = 1'b1;
            end""")

    cases_text = "\n\n".join(cases)

    return f"""// ============================================================
// Module      : control_unit
// File        : control_unit.v
// Description : Auto-generated, DENSE encoding mode. alu_op ({aow} bits)
//               and mem_to_reg ({mtw} bits) use minimal-width codes
//               computed by encoding_plan.py for exactly the instructions
//               this program uses -- see that file's docstring. Do not
//               hand-edit the widths or codes here without regenerating
//               alu_control.v / alu.v / the pipeline registers /
//               pipeline_top.v from the SAME plan, or the codes will
//               silently disagree between modules.
// ============================================================
`timescale 1ns / 1ps

module control_unit (
    input      [6:0]  opcode,
    input      [4:0]  rd,
    output reg        branch,
    output reg        mem_read,
    output reg [{mtw - 1}:0]  mem_to_reg,
    output reg [{aow - 1}:0]  alu_op,
    output reg        mem_write,
    output reg        alu_src,
    output reg        reg_write,
    output reg        jump,
    output reg        jalr
);

    reg reg_write_internal;

    always @(*) begin
        branch             = 1'b0;
        mem_read           = 1'b0;
        mem_to_reg         = {mtr('alu')};
        alu_op             = {aow}'d0;
        mem_write          = 1'b0;
        alu_src            = 1'b0;
        reg_write_internal = 1'b0;
        jump               = 1'b0;
        jalr               = 1'b0;

        case (opcode)

{cases_text}

            default: begin
            end
        endcase

        reg_write = (rd == 5'b00000) ? 1'b0 : reg_write_internal;
    end

endmodule
"""


# ---------------------------------------------------------------------------
# alu_control.v
# ---------------------------------------------------------------------------

def gen_alu_control(plan: dict, instructions_used: set) -> str:
    aow = plan["alu_op_width"]
    acw = plan["alu_control_width"]
    aoc = plan["alu_op_codes"]
    acc = plan["alu_control_codes"]

    def aop(name: str) -> str:
        return f"{aow}'d{aoc[name]}"

    def actl(name: str) -> str:
        return f"{acw}'d{acc[name]}"

    default_op = actl("ADD")  # ADD is always present in the plan

    funct3_cases = []
    if {"add", "addi"} & instructions_used:
        if "SUB" in acc:
            # add (R-type) and sub share funct3=000, disambiguated by
            # funct7 -- only meaningful (and only safe to reference) if
            # "sub" (or a branch, which also needs SUB) was actually
            # profiled as used, since that's what puts "SUB" in the plan.
            funct3_cases.append(f"""                    3'b000: begin
                        if (is_rtype && funct7)
                            alu_control = {actl('SUB')};
                        else
                            alu_control = {actl('ADD')};
                    end""")
        else:
            # sub was never used by this program -- no need for the
            # funct7 disambiguation at all, and no valid SUB code exists
            # in the plan to reference. Every funct3=000 R/I-type ALU
            # instruction is add/addi in that case.
            funct3_cases.append(f"                    3'b000: alu_control = {actl('ADD')};")
    if {"and", "andi"} & instructions_used:
        funct3_cases.append(f"                    3'b111: alu_control = {actl('AND')};")
    if {"or", "ori"} & instructions_used:
        funct3_cases.append(f"                    3'b110: alu_control = {actl('OR')};")
    if {"xor", "xori"} & instructions_used:
        funct3_cases.append(f"                    3'b100: alu_control = {actl('XOR')};")
    if {"sll", "slli"} & instructions_used:
        funct3_cases.append(f"                    3'b001: alu_control = {actl('SLL')};")
    if {"srl", "srli", "sra", "srai"} & instructions_used:
        srl_present = bool({"srl", "srli"} & instructions_used)
        sra_present = bool({"sra", "srai"} & instructions_used)
        if srl_present and sra_present:
            funct3_cases.append(f"""                    3'b101: begin
                        if (funct7)
                            alu_control = {actl('SRA')};
                        else
                            alu_control = {actl('SRL')};
                    end""")
        elif sra_present:
            funct3_cases.append(f"                    3'b101: alu_control = {actl('SRA')};")
        else:
            funct3_cases.append(f"                    3'b101: alu_control = {actl('SRL')};")
    if {"slt", "slti"} & instructions_used:
        funct3_cases.append(f"                    3'b010: alu_control = {actl('SLT')};")
    if {"sltu", "sltiu"} & instructions_used:
        funct3_cases.append(f"                    3'b011: alu_control = {actl('SLTU')};")

    funct3_text = "\n".join(funct3_cases)

    has_branch = bool(instructions_used & ep.BRANCH_SET)
    has_lui = "lui" in instructions_used
    has_ialu = bool(instructions_used & (ep.R_TYPE_SET | ep.I_ALU_SET))

    op_cases = []
    if bool(instructions_used & (ep.LOAD_SET | ep.STORE_SET | ep.JALR_SET | ep.AUIPC_SET | ep.JAL_SET)):
        op_cases.append(f"            {aop('addfam')}: alu_control = {actl('ADD')};")
    if has_branch:
        op_cases.append(f"            {aop('branch')}: alu_control = {actl('SUB')};")
    if has_ialu:
        op_cases.append(f"""            {aop('ialu')}: begin
                case (funct3)
{funct3_text}
                    default: alu_control = {default_op};
                endcase
            end""")
    if has_lui:
        op_cases.append(f"            {aop('lui')}: alu_control = {actl('LUIPASS')};")

    op_cases_text = "\n\n".join(op_cases)

    return f"""// ============================================================
// Module      : alu_control
// File        : alu_control.v
// Description : Auto-generated, DENSE encoding mode. See control_unit.v's
//               header -- alu_op ({aow} bits) and alu_control ({acw} bits)
//               widths/codes come from the same encoding_plan.py computed
//               from this program's actual instructions.
// ============================================================
`timescale 1ns / 1ps

module alu_control (
    input      [{aow - 1}:0]  alu_op,
    input      [2:0]  funct3,
    input             funct7,
    input             is_rtype,
    output reg [{acw - 1}:0]  alu_control
);

    always @(*) begin
        case (alu_op)
{op_cases_text}

            default: alu_control = {default_op};
        endcase
    end

endmodule
"""


# ---------------------------------------------------------------------------
# alu.v
# ---------------------------------------------------------------------------

_ALU_OP_RHS = {
    "AND": "a & b",
    "OR": "a | b",
    "ADD": "a + b",
    "XOR": "a ^ b",
    "SLL": "a << b[4:0]",
    "SRL": "a >> b[4:0]",
    "SUB": "a - b",
    "SRA": "$signed(a) >>> b[4:0]",
    "SLT": "($signed(a) < $signed(b)) ? 32'd1 : 32'd0",
    "SLTU": "(a < b) ? 32'd1 : 32'd0",
    "LUIPASS": "b",
}


def gen_alu(plan: dict) -> str:
    acw = plan["alu_control_width"]
    acc = plan["alu_control_codes"]

    def actl(name: str) -> str:
        return f"{acw}'d{acc[name]}"

    cases = []
    for name in sorted(acc.keys(), key=lambda n: acc[n]):
        rhs = _ALU_OP_RHS[name]
        cases.append(f"            {actl(name)}: result = {rhs};  // {name}")
    cases_text = "\n".join(cases)

    # overflow is only meaningful (and only ever gated true) when SUB is
    # actually part of the plan; if it isn't, no branch/sub logic exists
    # to consume it anyway, so gate it permanently false rather than
    # risk a KeyError or a meaningless comparison against a code that
    # doesn't exist.
    overflow_gate = f"(alu_control == {actl('SUB')})" if "SUB" in acc else "1'b0"

    return f"""// ============================================================
// Module      : ALU
// File        : alu.v
// Description : Auto-generated, DENSE encoding mode. alu_control is
//               {acw} bits, using codes computed by encoding_plan.py for
//               exactly the operations this program's instructions
//               require -- see control_unit.v's header for why these
//               must stay in sync with alu_control.v.
//
// Included operations: {', '.join(sorted(acc.keys(), key=lambda n: acc[n]))}
// ============================================================
`timescale 1ns / 1ps

module alu (
    input      [31:0] a,
    input      [31:0] b,
    input      [{acw - 1}:0]  alu_control,
    output reg [31:0] result,
    output            zero,
    output            negative,
    output            overflow,
    output            carry_out
);

    wire [32:0] sub_result = {{1'b0, a}} - {{1'b0, b}};

    assign zero      = (result == 32'h0);
    assign negative  = result[31];
    assign overflow  = (a[31] ^ b[31]) & (a[31] ^ result[31]) & {overflow_gate};
    assign carry_out = sub_result[32];

    always @(*) begin
        case (alu_control)
{cases_text}
            default: result = 32'h0;
        endcase
    end

endmodule
"""


def main(argv=None) -> int:
    argv = argv or sys.argv
    if len(argv) != 3:
        print("Usage: python3 tools/gen_dense_control.py <insts.json> <outdir>")
        return 1

    inst_json = Path(argv[1])
    outdir = Path(argv[2])
    outdir.mkdir(parents=True, exist_ok=True)

    summary = json.loads(inst_json.read_text(encoding="utf-8"))
    instructions_used = set(summary.get("instructions_used", []))

    plan = ep.compute_plan(instructions_used)

    (outdir / "control_unit.v").write_text(gen_control_unit(plan, instructions_used), encoding="utf-8")
    (outdir / "alu_control.v").write_text(gen_alu_control(plan, instructions_used), encoding="utf-8")
    (outdir / "alu.v").write_text(gen_alu(plan), encoding="utf-8")

    plan_path = outdir / "encoding_plan.json"
    plan_path.write_text(json.dumps(plan, indent=2), encoding="utf-8")

    print(f"Generated {outdir / 'control_unit.v'}")
    print(f"Generated {outdir / 'alu_control.v'}")
    print(f"Generated {outdir / 'alu.v'}")
    print(f"Wrote {plan_path} (consumed by gen_pipeline_regs.py and gen_pipeline_and_tb.py)")
    print(f"alu_op_width={plan['alu_op_width']} alu_control_width={plan['alu_control_width']} mem_to_reg_width={plan['mem_to_reg_width']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())